# Generated by Django 2.2.14 on 2020-08-10 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('default_stripe_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit_label', models.CharField(max_length=255)),
                ('billing_interval_value', models.PositiveSmallIntegerField()),
                ('billing_interval_unit', models.CharField(choices=[('D', 'Day'), ('M', 'Month'), ('W', 'Week')], max_length=1)),
                ('billing_type', models.CharField(choices=[('R', 'Recurring'), ('M', 'Metered')], max_length=1)),
                ('tiers_type', models.CharField(choices=[('V', 'Volume'), ('G', 'Graduated')], max_length=1)),
                ('aggregation_type', models.CharField(blank=True, choices=[('M', 'Maximum value over period'), ('S', 'Sum over period'), ('E', 'Last ever value'), ('P', 'Last value in period')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_billed', models.DateTimeField()),
                ('last_bill_attempted', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.RecurringPlan')),
                ('state', models.CharField(choices=[('A', 'Active'), ('P', 'Past due'), ('C', 'Cancelled')], default='A', max_length=1)),
                ('amount_unpaid', models.DecimalField(decimal_places=2, default='0', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPlanTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=14, max_digits=28)),
                ('flat_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.RecurringPlan')),
            ],
            options={
                'ordering': ('last_unit', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('usage_units', models.PositiveIntegerField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Subscription')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('key_auth', models.TextField()),
                ('key_p256dh', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BACSMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SEPAMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descriptor', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
                ('state', models.CharField(choices=[('P', 'Pending'), ('S', 'Processing'), ('F', 'Failed'), ('C', 'Completed')], default='P', max_length=1)),
                ('type', models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('E', 'SEPA Direct Debit'), ('S', 'Sources'), ('A', 'Charges'), ('H', 'Checkout'), ('M', 'Manual')], default='B', max_length=1)),
                ('type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('is_reversal', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChargeState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('return_uri', models.URLField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
                ('ledger_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_state', to='billing.LedgerItem')),
                ('payment_ledger_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_state_payment_set', to='billing.LedgerItem')),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
