# Generated by Django 2.2.16 on 2020-09-02 14:04

import as207960_utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_squashed_0019_auto_20200728_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacsmandate',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chargestate',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_charge', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_ledgeritem', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recurringplan',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_recurringplan', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recurringplantier',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_recurringplantier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sepamandate',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_subscription', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Past due'), ('C', 'Cancelled')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subscriptionusage',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_subscriptionusage', primary_key=True, serialize=False),
        ),
    ]
