# Generated by Django 3.0.5 on 2020-04-30 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_ledgeritem_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='type_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
