# Generated by Django 2.2.16 on 2020-09-04 09:32

import as207960_utils.models
import billing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200902_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_invoice', primary_key=True, serialize=False)),
                ('ref', models.CharField(default=billing.models.make_invoice_ref, max_length=100)),
                ('state', models.CharField(choices=[('D', 'Draft'), ('O', 'Outstanding'), ('P', 'Past due'), ('C', 'Paid')], max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFee',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_invoicefee', primary_key=True, serialize=False)),
                ('descriptor', models.CharField(max_length=255)),
                ('rate_per_unit', models.DecimalField(decimal_places=14, max_digits=28)),
                ('units', models.DecimalField(decimal_places=14, max_digits=28)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDiscount',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_invoicediscount', primary_key=True, serialize=False)),
                ('descriptor', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice')),
            ],
        ),
    ]
