# Generated by Django 2.2.17 on 2020-11-02 23:04

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_invoicediscount_invoicefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_gc_mandate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('E', 'SEPA Direct Debit'), ('O', 'SOFORT'), ('G', 'giropay'), ('N', 'Bancontact'), ('P', 'EPS'), ('I', 'iDEAL'), ('2', 'Przelewy24'), ('D', 'GoCardless'), ('S', 'Sources'), ('A', 'Charges'), ('H', 'Checkout'), ('M', 'Manual')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='ACHMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
