# Generated by Django 2.2.17 on 2020-11-03 08:47

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20201102_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PADMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GCSEPAMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GCBACSMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetalingsserviceMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BECSNZMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BECSMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutogiroMandate',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_mandate', primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
