# Generated by Django 3.0.5 on 2020-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200430_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgeritem',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='account',
            name='default_stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA')], default='B', max_length=1),
        ),
    ]
