# Generated by Django 3.0.5 on 2020-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20200430_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=20)),
            ],
        ),
    ]
