# Generated by Django 2.2.17 on 2020-11-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_autogiromandate_becsmandate_becsnzmandate_betalingsservicemandate_gcbacsmandate_gcsepamandate_padman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeritem',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Processing (cancellable)'), ('S', 'Processing'), ('F', 'Failed'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
