# Generated by Django 3.0.5 on 2020-05-14 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('descriptor', models.CharField(max_length=25)),
                ('unit_label', models.CharField(max_length=255)),
                ('billing_interval_value', models.PositiveSmallIntegerField()),
                ('billing_interval_unit', models.CharField(choices=[('D', 'Day'), ('M', 'Month'), ('W', 'Week')], max_length=1)),
                ('billing_type', models.CharField(choices=[('R', 'Recurring'), ('M', 'Metered')], max_length=1)),
                ('tiers_type', models.CharField(choices=[('V', 'Volume'), ('G', 'Graduated')], max_length=1)),
                ('aggregation_type', models.CharField(blank=True, choices=[('M', 'Maximum value over period'), ('S', 'Sum over period'), ('E', 'Last ever value'), ('P', 'Last value in period')], max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('S', 'Sources')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('usage_units', models.PositiveIntegerField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.RecurringPlan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_billed', models.DateTimeField()),
                ('last_bill_attempted', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.RecurringPlan')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPlanTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=14, max_digits=28)),
                ('flat_fee', models.DecimalField(decimal_places=2, max_digits=9)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.RecurringPlan')),
            ],
            options={
                'ordering': ['last_unit'],
            },
        ),
    ]
