# Generated by Django 2.2.17 on 2020-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20201103_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestate',
            name='notif_queue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
