# Generated by Django 3.0.5 on 2020-05-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_recurringplan_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionusage',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Subscription'),
        ),
    ]
