# Generated by Django 3.0.5 on 2020-05-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20200515_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringplantier',
            options={'ordering': ('last_unit', 'id')},
        ),
        migrations.AlterModelOptions(
            name='subscriptionusage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('key_auth', models.TextField()),
                ('key_p256dh', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
            ],
        ),
    ]
