# Generated by Django 2.2.17 on 2020-11-23 13:29

import as207960_utils.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20201123_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownstripepaymentmethod',
            name='country_code',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountbillingaddress',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='billing_billingaddress   ', primary_key=True, serialize=False),
        ),
    ]
