# Generated by Django 3.0.5 on 2020-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20200516_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Past due'), ('C', 'Cancelled')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
