# Generated by Django 3.0.5 on 2020-05-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_subscription_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('S', 'Sources'), ('M', 'Manual')], default='B', max_length=1),
        ),
    ]
