# Generated by Django 3.0.5 on 2020-06-28 19:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20200612_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('E', 'SEPA Direct Debit'), ('S', 'Sources'), ('H', 'Checkout'), ('M', 'Manual')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='SEPAMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mandate_id', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
