# Generated by Django 2.2.17 on 2020-11-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20201124_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestate',
            name='ready_to_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
