# Generated by Django 2.2.17 on 2020-11-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_chargestate_ready_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestate',
            name='evidence_ach_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.ACHMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_autogiro_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.AutogiroMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_bacs_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.BACSMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_becs_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.BECSMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_becs_nz_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.BECSNZMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_betalingsservice_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.BetalingsserviceMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_gc_bacs_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.GCBACSMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_gc_sepa_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.GCSEPAMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_pad_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.PADMandate'),
        ),
        migrations.AddField(
            model_name='chargestate',
            name='evidence_sepa_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.SEPAMandate'),
        ),
    ]
