# Generated by Django 3.0.5 on 2020-07-02 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20200630_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('E', 'SEPA Direct Debit'), ('S', 'Sources'), ('A', 'Charges'), ('H', 'Checkout'), ('M', 'Manual')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='ChargeState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('return_uri', models.URLField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Account')),
                ('ledger_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_state_set', to='billing.LedgerItem')),
                ('payment_ledger_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_state_payment_set', to='billing.LedgerItem')),
            ],
        ),
    ]
