# Generated by Django 3.0.5 on 2020-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_auto_20200702_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestate',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
