# Generated by Django 2.2.17 on 2020-11-26 11:10

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_chargestate_can_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='amount_unpaid',
        ),
        migrations.AddField(
            model_name='chargestate',
            name='completed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='last_state_change_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='failed_bill_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_subscriptioncharge', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('last_bill_attempted', models.DateTimeField()),
                ('failed_bill_attempts', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('ledger_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.LedgerItem')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Subscription')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
