# Generated by Django 2.2.17 on 2020-11-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20201126_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncharge',
            name='ledger_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.LedgerItem'),
        ),
    ]
