# Generated by Django 2.2.14 on 2020-07-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20200707_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargestate',
            name='ledger_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_state', to='billing.LedgerItem'),
        ),
    ]
