# Generated by Django 2.2.17 on 2020-11-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_auto_20201126_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringplan',
            name='notif_queue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='is_setup_charge',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(choices=[('E', 'Pending'), ('A', 'Active'), ('P', 'Past due'), ('C', 'Cancelled')], max_length=1),
        ),
    ]
