# Generated by Django 2.2.17 on 2020-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_auto_20201126_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbillingaddress',
            name='vat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VAT ID (without country prefix)'),
        ),
        migrations.AddField(
            model_name='accountbillingaddress',
            name='vat_id_verification_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
