# Generated by Django 2.2.17 on 2020-12-01 20:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_auto_20201130_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_current', to='billing.AccountBillingAddress'),
        ),
        migrations.AlterField(
            model_name='accountbillingaddress',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='knownstripepaymentmethod',
            name='country_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
