# Generated by Django 2.2.17 on 2020-12-07 17:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_auto_20201201_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='charged_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='evidence_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.AccountBillingAddress'),
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
