# Generated by Django 2.2.17 on 2020-12-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_auto_20201207_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='evidence_stripe_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.KnownStripePaymentMethod'),
        ),
    ]
