# Generated by Django 2.2.17 on 2020-12-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_auto_20201228_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargestate',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_ach_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_autogiro_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_bacs_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_bank_account',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_becs_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_becs_nz_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_betalingsservice_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_billing_address',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_gc_bacs_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_gc_sepa_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_pad_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_sepa_mandate',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='evidence_stripe_pm',
        ),
        migrations.RemoveField(
            model_name='chargestate',
            name='vat_rate',
        ),
    ]
