# Generated by Django 2.2.17 on 2020-12-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_auto_20201228_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargestate',
            name='completed_timestamp',
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='completed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
