# Generated by Django 2.2.17 on 2020-12-29 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_auto_20201228_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='default_gc_mandate_id',
        ),
        migrations.AddField(
            model_name='account',
            name='default_ach_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.ACHMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_autogiro_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.AutogiroMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_bacs_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.BACSMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_becs_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.BECSMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_becs_nz_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.BECSNZMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_betalingsservice_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.BetalingsserviceMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_gc_bacs_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.GCBACSMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_gc_sepa_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.GCSEPAMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_pad_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.PADMandate'),
        ),
        migrations.AddField(
            model_name='account',
            name='default_sepa_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_accounts', to='billing.SEPAMandate'),
        ),
    ]
