# Generated by Django 2.2.17 on 2021-01-05 14:12

from django.db import migrations, models
import django.db.models.deletion
import billing.models


def set_reversal_items(apps, schema_editor):
    LedgerItem = apps.get_model('billing', 'LedgerItem')
    for reversal_ledger_item in LedgerItem.objects.filter(is_reversal=True):
        ledger_item = LedgerItem.objects.filter(
            type=billing.models.LedgerItem.TYPE_CHARGE,
            type_id=reversal_ledger_item.type_id,
            is_reversal=False
        ).first()
        reversal_ledger_item.reversal_for = ledger_item
        reversal_ledger_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_auto_20201229_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='reversal_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.LedgerItem'),
        ),
        migrations.RunPython(set_reversal_items)
    ]
