# Generated by Django 2.2.17 on 2021-01-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_ledgeritem_reversal_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeritem',
            name='reversal_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='billing.LedgerItem'),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('E', 'SEPA Direct Debit'), ('O', 'SOFORT'), ('G', 'giropay'), ('N', 'Bancontact'), ('P', 'EPS'), ('I', 'iDEAL'), ('2', 'Przelewy24'), ('D', 'GoCardless'), ('S', 'Sources'), ('A', 'Charges'), ('H', 'Checkout'), ('M', 'Manual'), ('R', 'Stripe refund'), ('T', 'Stripe bank transfer')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='AccountStripeVirtualUKBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_code', models.CharField(max_length=6)),
                ('account_number', models.CharField(max_length=11)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
            ],
        ),
    ]
