# Generated by Django 2.2.17 on 2021-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_auto_20210105_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exclude_from_accounting',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
