# Generated by Django 2.2.17 on 2021-02-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_auto_20210124_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='stripe_climate_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
