# Generated by Django 2.2.17 on 2021-02-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_ledgeritem_eur_exchange_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptioncharge',
            old_name='ledger_item',
            new_name='last_ledger_item',
        ),
        migrations.RemoveField(
            model_name='subscriptioncharge',
            name='failed_bill_attempts',
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='subscription_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_items', to='billing.SubscriptionCharge'),
        ),
    ]
