# Generated by Django 2.2.17 on 2021-02-07 16:20

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_billingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeagentInvoice',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='billing_freeagentinvoice', primary_key=True, serialize=False)),
                ('freeagent_id', models.CharField(max_length=255)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Account')),
                ('ledger_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.LedgerItem')),
            ],
        ),
    ]
