# Generated by Django 2.2.17 on 2021-02-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_freeagentinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeagentinvoice',
            name='ledger_item',
        ),
        migrations.AddField(
            model_name='freeagentinvoice',
            name='charge_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.ChargeState'),
        ),
    ]
