# Generated by Django 2.2.17 on 2021-02-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_account_freeagent_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeagentinvoice',
            name='temp_account',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
