# Generated by Django 2.2.17 on 2021-02-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_freeagentinvoice_temp_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='freeagent_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.FreeagentInvoice'),
        ),
    ]
