# Generated by Django 2.2.22 on 2021-05-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_auto_20210208_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestate',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
