# Generated by Django 2.2.24 on 2021-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_auto_20210627_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='try_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
