# Generated by Django 2.2.24 on 2022-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0046_ledgeritem_try_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='next_invoice_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ledgeritem',
            name='invoice_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
