# Generated by Django 2.2.28 on 2023-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_auto_20220127_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeritem',
            name='krw_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
