# Generated by Django 5.0.4 on 2024-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0049_account_cloudflare_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="crypto_allowed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
