# Generated by Django 5.0.4 on 2024-07-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0051_alter_ledgeritem_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="netbox_account_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
