# Generated by Django 5.0.14 on 2025-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0052_account_netbox_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbillingaddress',
            name='residency_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ledgeritem',
            name='type',
            field=models.CharField(choices=[('B', 'Charge'), ('C', 'Card'), ('F', 'BACS/Faster payments/SEPA'), ('E', 'SEPA Direct Debit'), ('O', 'SOFORT'), ('G', 'giropay'), ('N', 'Bancontact'), ('P', 'EPS'), ('I', 'iDEAL'), ('2', 'Przelewy24'), ('D', 'GoCardless'), ('S', 'Sources'), ('A', 'Charges'), ('H', 'Checkout'), ('M', 'Manual'), ('Q', 'Manual Refund'), ('R', 'Stripe refund'), ('T', 'Stripe bank transfer'), ('L', 'GoCardless payment request'), ('Y', 'Coinbase Crypto')], default='B', max_length=1),
        ),
    ]
