kind: ConfigMap
apiVersion: v1
metadata:
  name: billing-django-conf
data:
  HOST: "billing.as207960.net,billing-nginx"
  DJANGO_SETTINGS_MODULE: as207960_billing.settings
  EXTERNAL_URL: "https://billing.as207960.net"
  SENTRY_ENVIRONMENT: "prod"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net/"
  KEYCLOAK_REALM: master
  KEYCLOAK_SCOPES: "openid email profile"
  KEYCLOAK_CLIENT_ID: "billing"
  STRIPE_PUBLIC_KEY: "pk_live_VLsjEC8QBoN5rQWW0rfVccqW00VzaknDP3"
  DB_HOST: "cockroachdb"
  DB_NAME: "billing"
  EMAIL_FROM: "=?UTF-8?q?AS207960=20Billing?= <billing@as207960.net>"
  S3_ENDPOINT: "https://s3.as207960.net"
  S3_REGION: "garage"
  S3_BUCKET: "billing-django"
  S3_ACCESS_KEY_ID: "GKa8076ec9a72effa68e2f4dd7"
  S3_CUSTOM_DOMAIN: "billing-django.content.as207960.net"
  STATIC_URL: "https://billing-django.content.as207960.net/"
  MEDIA_URL: "https://billing-django.content.as207960.net/"
  LISTMONK_TEMPLATE_ID: "3"
  LISTMONK_URL: "https://listmonk.as207960.net"
  FREEAGENT_BASE_URL: "https://api.freeagent.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-django
  labels:
    app: billing
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: billing
        part: django
    spec:
      initContainers:
        - name: django
          image: as207960/billing-django:(version)
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          ports:
            - containerPort: 8000
          envFrom: &envFrom
            - configMapRef:
                name: billing-django-conf
            - secretRef:
                name: billing-db-creds
              prefix: "DB_"
            - secretRef:
                name: billing-django-secret
            - secretRef:
                name: billing-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: billing-stripe-secret
            - secretRef:
                name: billing-monzo-secret
            - secretRef:
                name: billing-open-exchange-secret
            - secretRef:
                name: billing-webpush
            - secretRef:
                name: billing-flux
              prefix: "FLUX_"
            - secretRef:
                name: billing-hmrc
              prefix: "HMRC_"
            - secretRef:
                name: billing-gc
              prefix: "GOCARDLESS_"
            - secretRef:
                name: billing-xfw
              prefix: "TRANSFERWISE_"
            - secretRef:
                name: billing-rpc
            - secretRef:
                name: billing-s3
            - secretRef:
                name: billing-freeagent
              prefix: "FREEAGENT_"
            - secretRef:
                name: billing-cloudflare
              prefix: "CLOUDFLARE_"
      containers:
        - name: gunicorn
          image: as207960/billing-django:(version)
          imagePullPolicy: IfNotPresent
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--timeout=90", "as207960_billing.wsgi:application"]
          ports:
            - containerPort: 8000
          envFrom: *envFrom
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-django
spec:
  podSelector:
    matchLabels:
      app: billing
      part: django
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: billing
          part: nginx
    ports:
    - protocol: TCP
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-rpc
  labels:
    app: billing
    part: rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
      part: rpc
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: billing
        part: rpc
    spec:
      containers:
        - name: rpc
          image: as207960/billing-django:(version)
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "python3 manage.py run-rpc"]
          envFrom:
            - configMapRef:
                name: billing-django-conf
            - secretRef:
                name: billing-db-creds
              prefix: "DB_"
            - secretRef:
                name: billing-django-secret
            - secretRef:
                name: billing-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: billing-stripe-secret
            - secretRef:
                name: billing-monzo-secret
            - secretRef:
                name: billing-open-exchange-secret
            - secretRef:
                name: billing-webpush
            - secretRef:
                name: billing-flux
              prefix: "FLUX_"
            - secretRef:
                name: billing-hmrc
              prefix: "HMRC_"
            - secretRef:
                name: billing-gc
              prefix: "GOCARDLESS_"
            - secretRef:
                name: billing-xfw
              prefix: "TRANSFERWISE_"
            - secretRef:
                name: billing-rpc
            - secretRef:
                name: billing-s3
            - secretRef:
                name: billing-freeagent
              prefix: "FREEAGENT_"
            - secretRef:
                name: billing-cloudflare
              prefix: "CLOUDFLARE_"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-rpc
spec:
  podSelector:
    matchLabels:
      app: billing
      part: rpc
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-keycloak-events
spec:
  podSelector:
    matchLabels:
      app: billing
      part: keycloak-events
  policyTypes:
  - Ingress
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: billing-get-exchange
spec:
  schedule: "17 */4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing
            part: get-exchange
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py sync-exchange"]
              envFrom:
                - configMapRef:
                    name: billing-django-conf
                - secretRef:
                    name: billing-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-secret
                - secretRef:
                    name: billing-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-secret
                - secretRef:
                    name: billing-monzo-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-rpc
                - secretRef:
                    name: billing-s3
                - secretRef:
                    name: billing-freeagent
                  prefix: "FREEAGENT_"
                - secretRef:
                    name: billing-cloudflare
                  prefix: "CLOUDFLARE_"
          restartPolicy: OnFailure
#---
#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: billing-attempt-reconcile
#spec:
#  schedule: "00 4 * * *"
#  jobTemplate:
#    spec:
#      template:
#        metadata:
#          annotations:
#            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
#        spec:
#          volumes:
#            - name: static
#              persistentVolumeClaim:
#                claimName: billing-django-static
#            - name: media
#              persistentVolumeClaim:
#                claimName: billing-django-media
#          containers:
#            - name: django
#              image: as207960/billing-django:(version)
#              imagePullPolicy: IfNotPresent
#              command: ["sh", "-c", "python3 manage.py attempt-reconcile"]
#              volumeMounts:
#                - mountPath: "/app/static/"
#                  name: static
#                - mountPath: "/app/media/"
#                  name: media
#              envFrom:
#                - configMapRef:
#                    name: billing-django-conf
#                - secretRef:
#                    name: billing-db-creds
#                  prefix: "DB_"
#                - secretRef:
#                    name: billing-django-secret
#                - secretRef:
#                    name: billing-keycloak
#                  prefix: "KEYCLOAK_"
#                - secretRef:
#                    name: billing-stripe-secret
#                - secretRef:
#                    name: billing-monzo-secret
#                - secretRef:
#                    name: billing-open-exchange-secret
#                - secretRef:
#                    name: billing-webpush
#                - secretRef:
#                    name: billing-flux
#                  prefix: "FLUX_"
#                - secretRef:
#                    name: billing-hmrc
#                  prefix: "HMRC_"
#                - secretRef:
#                    name: billing-gc
#                  prefix: "GOCARDLESS_"
#                - secretRef:
#                    name: billing-xfw
#                  prefix: "TRANSFERWISE_"
#                - secretRef:
#                    name: billing-rpc
#          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: billing-run-billing
spec:
  schedule: "34 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing
            part: run-billing
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py run-billing"]
              envFrom:
                - configMapRef:
                    name: billing-django-conf
                - secretRef:
                    name: billing-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-secret
                - secretRef:
                    name: billing-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-secret
                - secretRef:
                    name: billing-monzo-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-rpc
                - secretRef:
                    name: billing-s3
                - secretRef:
                    name: billing-freeagent
                  prefix: "FREEAGENT_"
                - secretRef:
                    name: billing-cloudflare
                  prefix: "CLOUDFLARE_"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: billing-update-pending
spec:
  schedule: "16 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing
            part: update-pending
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py update-pending"]
              envFrom:
                - configMapRef:
                    name: billing-django-conf
                - secretRef:
                    name: billing-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-secret
                - secretRef:
                    name: billing-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-secret
                - secretRef:
                    name: billing-monzo-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-rpc
                - secretRef:
                    name: billing-s3
                - secretRef:
                    name: billing-freeagent
                  prefix: "FREEAGENT_"
                - secretRef:
                    name: billing-cloudflare
                  prefix: "CLOUDFLARE_"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: billing-fail-old
spec:
  schedule: "42 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing
            part: fail-old
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py fail-old"]
              envFrom:
                - configMapRef:
                    name: billing-django-conf
                - secretRef:
                    name: billing-db-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-secret
                - secretRef:
                    name: billing-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-secret
                - secretRef:
                    name: billing-monzo-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-rpc
                - secretRef:
                    name: billing-s3
                - secretRef:
                    name: billing-freeagent
                  prefix: "FREEAGENT_"
                - secretRef:
                    name: billing-cloudflare
                  prefix: "CLOUDFLARE_"
          restartPolicy: OnFailure
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-cronjob
spec:
  podSelector:
    matchLabels:
      app: billing
      part-type: cronjob
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Service
metadata:
  name: billing-django
  labels:
    app: billing
    part: django
spec:
  selector:
    app: billing
    part: django
  ports:
    - port: 8000
      targetPort: 8000
      name: gunicorn
