kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: billing-django-test-static
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: billing-django-test-media
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: billing-django-test-conf
data:
  HOST: "billing.test.as207960.net,billing-nginx-test"
  DJANGO_SETTINGS_MODULE: as207960_billing.settings
  EXTERNAL_URL: "https://billing.test.as207960.net"
  SENTRY_ENVIRONMENT: "test"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net/"
  KEYCLOAK_REALM: test
  KEYCLOAK_SCOPES: "openid email profile"
  KEYCLOAK_CLIENT_ID: "billing"
  STRIPE_PUBLIC_KEY: "pk_test_HiLhXV0p2Gk4HzYr5S5vpmbi00pSy0cAVL"
  DB_HOST: "cockroachdb"
  DB_NAME: "billing-test"
  EMAIL_FROM: "=?UTF-8?q?AS207960=20Billing=20[TEST]?= <billing-test@as207960.net>"
  IS_TEST: "true"
  STRIPE_CLIMATE: "true"
  LISTMONK_TEMPLATE_ID: "3"
  LISTMONK_URL: "https://listmonk.as207960.net"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-django-test
  labels:
    app: billing-test
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-test
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: billing-test
        part: django
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: billing-django-test-static
        - name: media
          persistentVolumeClaim:
            claimName: billing-django-test-media
      initContainers:
        - name: django
          image: as207960/billing-django:(version)
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
          envFrom:
            - configMapRef:
                name: billing-django-test-conf
            - secretRef:
                name: billing-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: billing-django-test-secret
            - secretRef:
                name: billing-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: billing-stripe-test-secret
            - secretRef:
                name: billing-monzo-test-secret
            - secretRef:
                name: billing-open-exchange-secret
            - secretRef:
                name: billing-webpush
            - secretRef:
                name: billing-flux-test
              prefix: "FLUX_"
            - secretRef:
                name: billing-hmrc-test
              prefix: "HMRC_"
            - secretRef:
                name: billing-gc-test
              prefix: "GOCARDLESS_"
            - secretRef:
                name: billing-xfw-test
              prefix: "TRANSFERWISE_"
            - secretRef:
                name: billing-test-rpc
      containers:
        - name: gunicorn
          image: as207960/billing-django:(version)
          imagePullPolicy: IfNotPresent
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--timeout=90", "as207960_billing.wsgi:application"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
          envFrom:
            - configMapRef:
                name: billing-django-test-conf
            - secretRef:
                name: billing-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: billing-django-test-secret
            - secretRef:
                name: billing-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: billing-stripe-test-secret
            - secretRef:
                name: billing-monzo-test-secret
            - secretRef:
                name: billing-open-exchange-secret
            - secretRef:
                name: billing-webpush
            - secretRef:
                name: billing-flux-test
              prefix: "FLUX_"
            - secretRef:
                name: billing-hmrc-test
              prefix: "HMRC_"
            - secretRef:
                name: billing-gc-test
              prefix: "GOCARDLESS_"
            - secretRef:
                name: billing-xfw-test
              prefix: "TRANSFERWISE_"
            - secretRef:
                name: billing-test-rpc
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-test-django
spec:
  podSelector:
    matchLabels:
      app: billing-test
      part: django
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: billing-test
          part: nginx
    ports:
    - protocol: TCP
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-rpc-test
  labels:
    app: billing-test
    part: rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-test
      part: rpc
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: billing-test
        part: rpc
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: billing-django-test-static
        - name: media
          persistentVolumeClaim:
            claimName: billing-django-test-media
      containers:
        - name: rpc
          image: as207960/billing-django:(version)
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "python3 manage.py run-rpc"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
          envFrom:
            - configMapRef:
                name: billing-django-test-conf
            - secretRef:
                name: billing-db-test-creds
              prefix: "DB_"
            - secretRef:
                name: billing-django-test-secret
            - secretRef:
                name: billing-test-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: billing-stripe-test-secret
            - secretRef:
                name: billing-monzo-test-secret
            - secretRef:
                name: billing-open-exchange-secret
            - secretRef:
                name: billing-webpush
            - secretRef:
                name: billing-flux-test
              prefix: "FLUX_"
            - secretRef:
                name: billing-hmrc-test
              prefix: "HMRC_"
            - secretRef:
                name: billing-gc-test
              prefix: "GOCARDLESS_"
            - secretRef:
                name: billing-xfw-test
              prefix: "TRANSFERWISE_"
            - secretRef:
                name: billing-test-rpc
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-test-rpc
spec:
  podSelector:
    matchLabels:
      app: billing-test
      part: rpc
  policyTypes:
  - Ingress
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: billing-test-get-exchange
  labels:
    app: billing-test
    part: get-exchange
spec:
  schedule: "17 */4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing-test
            part: get-exchange
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          volumes:
            - name: static
              persistentVolumeClaim:
                claimName: billing-django-test-static
            - name: media
              persistentVolumeClaim:
                claimName: billing-django-test-media
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py sync-exchange"]
              volumeMounts:
                - mountPath: "/app/static/"
                  name: static
                - mountPath: "/app/media/"
                  name: media
              envFrom:
                - configMapRef:
                    name: billing-django-test-conf
                - secretRef:
                    name: billing-db-test-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-test-secret
                - secretRef:
                    name: billing-test-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-test-secret
                - secretRef:
                    name: billing-monzo-test-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux-test
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc-test
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc-test
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw-test
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-test-rpc
          restartPolicy: OnFailure
#---
#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: billing-test-attempt-reconcile
#  labels:
#    app: billing-test
#    part: attempt-reconcile
#spec:
#  schedule: "00 4 * * *"
#  jobTemplate:
#    spec:
#      template:
#        metadata:
#          annotations:
#            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
#        spec:
#          volumes:
#            - name: static
#              persistentVolumeClaim:
#                claimName: billing-django-test-static
#            - name: media
#              persistentVolumeClaim:
#                claimName: billing-django-test-media
#          containers:
#            - name: django
#              image: as207960/billing-django:(version)
#              imagePullPolicy: IfNotPresent
#              command: ["sh", "-c", "python3 manage.py attempt-reconcile"]
#              volumeMounts:
#                - mountPath: "/app/static/"
#                  name: static
#                - mountPath: "/app/media/"
#                  name: media
#              envFrom:
#                - configMapRef:
#                    name: billing-django-test-conf
#                - secretRef:
#                    name: billing-db-test-creds
#                  prefix: "DB_"
#                - secretRef:
#                    name: billing-django-test-secret
#                - secretRef:
#                    name: billing-test-keycloak
#                  prefix: "KEYCLOAK_"
#                - secretRef:
#                    name: billing-stripe-test-secret
#                - secretRef:
#                    name: billing-monzo-test-secret
#                - secretRef:
#                    name: billing-open-exchange-secret
#                - secretRef:
#                    name: billing-webpush
#                - secretRef:
#                    name: billing-flux-test
#                  prefix: "FLUX_"
#                - secretRef:
#                    name: billing-hmrc-test
#                  prefix: "HMRC_"
#                - secretRef:
#                    name: billing-gc-test
#                  prefix: "GOCARDLESS_"
#                - secretRef:
#                    name: billing-xfw-test
#                  prefix: "TRANSFERWISE_"
#                - secretRef:
#                    name: billing-test-rpc
#          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: billing-test-run-billing
  labels:
    app: billing-test
    part: run-billing
spec:
  schedule: "34 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing-test
            part: run-billing
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          volumes:
            - name: static
              persistentVolumeClaim:
                claimName: billing-django-test-static
            - name: media
              persistentVolumeClaim:
                claimName: billing-django-test-media
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py run-billing"]
              volumeMounts:
                - mountPath: "/app/static/"
                  name: static
                - mountPath: "/app/media/"
                  name: media
              envFrom:
                - configMapRef:
                    name: billing-django-test-conf
                - secretRef:
                    name: billing-db-test-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-test-secret
                - secretRef:
                    name: billing-test-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-test-secret
                - secretRef:
                    name: billing-monzo-test-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux-test
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc-test
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc-test
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw-test
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-test-rpc
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: billing-test-update-pending
  labels:
    app: billing-test
    part: update-pending
spec:
  schedule: "16 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing-test
            part: update-pending
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          volumes:
            - name: static
              persistentVolumeClaim:
                claimName: billing-django-test-static
            - name: media
              persistentVolumeClaim:
                claimName: billing-django-test-media
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py update-pending"]
              volumeMounts:
                - mountPath: "/app/static/"
                  name: static
                - mountPath: "/app/media/"
                  name: media
              envFrom:
                - configMapRef:
                    name: billing-django-test-conf
                - secretRef:
                    name: billing-db-test-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-test-secret
                - secretRef:
                    name: billing-test-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-test-secret
                - secretRef:
                    name: billing-monzo-test-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux-test
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc-test
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc-test
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw-test
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-test-rpc
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: billing-test-fail-old
  labels:
    app: billing-test
    part: fail-old
spec:
  schedule: "42 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: billing-test
            part: fail-old
            part-type: cronjob
          annotations:
            cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
        spec:
          volumes:
            - name: static
              persistentVolumeClaim:
                claimName: billing-django-test-static
            - name: media
              persistentVolumeClaim:
                claimName: billing-django-test-media
          containers:
            - name: django
              image: as207960/billing-django:(version)
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "python3 manage.py fail-old"]
              volumeMounts:
                - mountPath: "/app/static/"
                  name: static
                - mountPath: "/app/media/"
                  name: media
              envFrom:
                - configMapRef:
                    name: billing-django-test-conf
                - secretRef:
                    name: billing-db-test-creds
                  prefix: "DB_"
                - secretRef:
                    name: billing-django-test-secret
                - secretRef:
                    name: billing-test-keycloak
                  prefix: "KEYCLOAK_"
                - secretRef:
                    name: billing-stripe-test-secret
                - secretRef:
                    name: billing-monzo-test-secret
                - secretRef:
                    name: billing-open-exchange-secret
                - secretRef:
                    name: billing-webpush
                - secretRef:
                    name: billing-flux-test
                  prefix: "FLUX_"
                - secretRef:
                    name: billing-hmrc-test
                  prefix: "HMRC_"
                - secretRef:
                    name: billing-gc-test
                  prefix: "GOCARDLESS_"
                - secretRef:
                    name: billing-xfw-test
                  prefix: "TRANSFERWISE_"
                - secretRef:
                    name: billing-test-rpc
          restartPolicy: OnFailure
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-test-cronjob
spec:
  podSelector:
    matchLabels:
      app: billing-test
      part-type: cronjob
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Service
metadata:
  name: billing-django-test
  labels:
    app: billing-test
    part: django
spec:
  selector:
    app: billing-test
    part: django
  ports:
    - port: 8000
      targetPort: 8000
      name: gunicorn
