from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('account/', views.account_details, name='account_details'),
    path('account/export/', views.statement_export, name='statement_export'),
    path('top_up/', views.top_up, name='top_up'),
    path('top_up_card/', views.top_up_card, name='top_up_card'),
    path('top_up_bacs/', views.top_up_bacs, name='top_up_bacs'),
    path('top_up_bacs_direct_debit/', views.top_up_bacs_direct_debit, name='top_up_bacs_direct_debit'),
    # path('top_up_sepa_direct_debit/', views.top_up_sepa_direct_debit, name='top_up_sepa_direct_debit'),
    path('top_up_sofort/', views.top_up_sofort, name='top_up_sofort'),
    path('top_up_giropay/', views.top_up_giropay, name='top_up_giropay'),
    path('top_up_bancontact/', views.top_up_bancontact, name='top_up_bancontact'),
    path('top_up_eps/', views.top_up_eps, name='top_up_eps'),
    path('top_up_ideal/', views.top_up_ideal, name='top_up_ideal'),
    path('top_up_multibanco/', views.top_up_multibanco, name='top_up_multibanco'),
    path('top_up_p24/', views.top_up_p24, name='top_up_p24'),
    path('complete_top_up_card/<str:item_id>/', views.complete_top_up_card, name='complete_top_up_card'),
    path('complete_top_up_bacs/<str:item_id>/', views.complete_top_up_bacs, name='complete_top_up_bacs'),
    path('complete_top_up_sepa_direct_debit/<str:item_id>/', views.complete_top_up_sepa_direct_debit,
         name='complete_top_up_sepa_direct_debit'),
    path('complete_top_up_checkout/<str:item_id>/', views.complete_top_up_checkout, name='complete_top_up_checkout'),
    path('complete_top_up_sources/<str:item_id>/', views.complete_top_up_sources, name='complete_top_up_sources'),
    path('fail_top_up/<str:item_id>/', views.fail_top_up, name='fail_top_up'),
    path('complete_charge/<str:charge_id>/', views.complete_charge, name='complete_charge'),
    path('fail_charge/<str:charge_id>/', views.fail_charge, name='fail_charge'),
    path('add_card/', views.add_card, name='add_card'),
    path('edit_card/<pm_id>/', views.edit_card, name='edit_card'),
    path('add_bacs_direct_debit/', views.add_bacs_mandate, name='add_bacs_mandate'),
    path('edit_bacs_direct_debit/<str:m_id>/', views.edit_bacs_mandate, name='edit_bacs_mandate'),
    # path('add_sepa_direct_debit/', views.add_sepa_mandate, name='add_sepa_mandate'),
    # path('edit_sepa_direct_debit/<str:m_id>/', views.edit_sepa_mandate, name='edit_sepa_mandate'),
    path('edit_subscription/<str:s_id>/', views.edit_subscription, name='edit_subscription'),
    path('stripe_webhook/', views.stripe_webhook),
    path('monzo_webhook/<secret_key>/', views.monzo_webhook),
    path('charge_user/<user_id>/', views.charge_user),
    path('get_charge_state/<str:charge_state_id>/', views.get_charge_state),
    path('reverse_charge/', views.reverse_charge),
    path('subscribe_user/<user_id>/', views.subscribe_user),
    path('log_usage/<subscription_id>/', views.log_usage),
    path('convert_currency/', views.convert_currency),
    path('save_subscription/', views.save_subscription),
    path('sw.js', views.sw),
    path('accounts/', views.view_accounts, name='view_accounts'),
    path('accounts/<account_id>/', views.view_account, name='view_account'),
    path('accounts/edit_item/<item_id>/', views.edit_ledger_item, name='edit_ledger_item'),
    path('accounts/<account_id>/charge/', views.charge_account, name='charge_account'),
    path('accounts/<account_id>/top_up/', views.manual_top_up_account, name='manual_top_up_account'),
]
