# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geoip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgeoip.proto\x12\x05geoip\x1a\x1egoogle/protobuf/wrappers.proto\"F\n\x0cGeoIPRequest\x12+\n\tip_lookup\x18\x01 \x01(\x0b\x32\x16.geoip.IPLookupRequestH\x00\x42\t\n\x07message\"F\n\x0fIPLookupRequest\x12\x13\n\tipv4_addr\x18\x01 \x01(\x07H\x00\x12\x13\n\tipv6_addr\x18\x02 \x01(\x0cH\x00\x42\t\n\x07ip_addr\"\x81\x04\n\x10IPLookupResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.geoip.IPLookupResponse.IPLookupStatus\x12\x32\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32$.geoip.IPLookupResponse.IPLookupData\x1a\xca\x02\n\x0cIPLookupData\x12-\n\x07\x63ountry\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0bpostal_code\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\ttime_zone\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nmetro_code\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12.\n\x08latitude\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12/\n\tlongitude\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x14\n\x0csubdivisions\x18\x07 \x03(\t\"4\n\x0eIPLookupStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02OK\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geoip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEOIPREQUEST._serialized_start=54
  _GEOIPREQUEST._serialized_end=124
  _IPLOOKUPREQUEST._serialized_start=126
  _IPLOOKUPREQUEST._serialized_end=196
  _IPLOOKUPRESPONSE._serialized_start=199
  _IPLOOKUPRESPONSE._serialized_end=712
  _IPLOOKUPRESPONSE_IPLOOKUPDATA._serialized_start=328
  _IPLOOKUPRESPONSE_IPLOOKUPDATA._serialized_end=658
  _IPLOOKUPRESPONSE_IPLOOKUPSTATUS._serialized_start=660
  _IPLOOKUPRESPONSE_IPLOOKUPSTATUS._serialized_end=712
# @@protoc_insertion_point(module_scope)
